# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreatePort.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1262, 643)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMaximumSize(QtCore.QSize(260, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 258, 623))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 217, 107))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.com_showRate = QtWidgets.QComboBox(self.layoutWidget)
        self.com_showRate.setObjectName("com_showRate")
        self.com_showRate.addItem("")
        self.com_showRate.addItem("")
        self.com_showRate.addItem("")
        self.com_showRate.addItem("")
        self.com_showRate.addItem("")
        self.gridLayout.addWidget(self.com_showRate, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.com_showPort = QtWidgets.QComboBox(self.layoutWidget)
        self.com_showPort.setObjectName("com_showPort")
        self.gridLayout.addWidget(self.com_showPort, 0, 1, 1, 1)
        self.btn_openFile = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_openFile.setGeometry(QtCore.QRect(130, 130, 111, 41))
        self.btn_openFile.setObjectName("btn_openFile")
        self.btn_start = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_start.setGeometry(QtCore.QRect(10, 260, 111, 41))
        self.btn_start.setObjectName("btn_start")
        self.btn_end = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_end.setGeometry(QtCore.QRect(130, 260, 111, 41))
        self.btn_end.setObjectName("btn_end")
        self.text_showFile = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.text_showFile.setGeometry(QtCore.QRect(10, 180, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_showFile.setFont(font)
        self.text_showFile.setObjectName("text_showFile")
        self.btn_searchPort = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_searchPort.setGeometry(QtCore.QRect(10, 130, 116, 41))
        self.btn_searchPort.setObjectName("btn_searchPort")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(0, 410, 241, 181))
        self.groupBox.setObjectName("groupBox")
        self.text_showS = QtWidgets.QTextEdit(self.groupBox)
        self.text_showS.setGeometry(QtCore.QRect(10, 40, 211, 60))
        self.text_showS.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_showS.setFont(font)
        self.text_showS.setObjectName("text_showS")
        self.btn_clearS = QtWidgets.QPushButton(self.groupBox)
        self.btn_clearS.setGeometry(QtCore.QRect(10, 130, 101, 41))
        self.btn_clearS.setObjectName("btn_clearS")
        self.btn_send = QtWidgets.QPushButton(self.groupBox)
        self.btn_send.setGeometry(QtCore.QRect(130, 130, 101, 41))
        self.btn_send.setObjectName("btn_send")
        self.btn_sendFile = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.btn_sendFile.setGeometry(QtCore.QRect(30, 320, 185, 41))
        self.btn_sendFile.setObjectName("btn_sendFile")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMaximumSize(QtCore.QSize(828, 664))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.text_showRecord = QtWidgets.QTextEdit(self.tab)
        self.text_showRecord.setGeometry(QtCore.QRect(13, 84, 801, 511))
        self.text_showRecord.setMinimumSize(QtCore.QSize(381, 461))
        self.text_showRecord.setObjectName("text_showRecord")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(14, 54, 701, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_claerT1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_claerT1.setObjectName("btn_claerT1")
        self.horizontalLayout_2.addWidget(self.btn_claerT1)
        spacerItem = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.radio_show = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radio_show.setObjectName("radio_show")
        self.horizontalLayout_2.addWidget(self.radio_show)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "串口号"))
        self.com_showRate.setItemText(0, _translate("Form", "13824000"))
        self.com_showRate.setItemText(1, _translate("Form", "1382400"))
        self.com_showRate.setItemText(2, _translate("Form", "115200"))
        self.com_showRate.setItemText(3, _translate("Form", "9600"))
        self.com_showRate.setItemText(4, _translate("Form", "256000"))
        self.label_2.setText(_translate("Form", "波特率"))
        self.btn_openFile.setText(_translate("Form", "打开文件"))
        self.btn_start.setText(_translate("Form", "打开"))
        self.btn_end.setText(_translate("Form", "关闭"))
        self.btn_searchPort.setText(_translate("Form", "查找串口"))
        self.groupBox.setTitle(_translate("Form", "发送设置"))
        self.btn_clearS.setText(_translate("Form", "清除"))
        self.btn_send.setText(_translate("Form", "发送"))
        self.btn_sendFile.setText(_translate("Form", "发送文件"))
        self.text_showRecord.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_claerT1.setText(_translate("Form", "清空日志"))
        self.radio_show.setText(_translate("Form", "接收完成自动显示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "数据日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "文件展示"))

